# Generated by Django 3.2.6 on 2022-11-26 00:12

import blango_auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blango_auth', '0002_auto_20221020_2247'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', blango_auth.models.BlangoUserManager()),
            ],
        ),
    ]
